### ISSUE TITLE
NSFW! hentaitake.net

### ISSUE THREAD

**Issue by MonfGeiger** [jspenguin2017/AdBlockProtector#208]
this one is happening whenever I go to hentaitake.net; and yes, I am using recommended test settings, and still happens; here's the popup
![antiadblock msg](https://cloud.githubusercontent.com/assets/28603306/26091562/323d1bfc-39c9-11e7-8233-96b66ef1f705.JPG)

help is appreciated

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
try `@@||hentaitake.net^$elemhide`

**Comment by jspenguin2017** [comment]
Can't reproduce. Both the home page and one random article works. 
Does the block screen comes up immediately? Or after a significant delay?

**Comment by lain566** [comment]
@jspenguin2017 When you try to download a video

**Comment by uBlock-user** [comment]
All  download are hosted on 3rd party servers.

**Comment by jspenguin2017** [comment]
@lain566 I clicked a download link then go back, still can't reproduce.

**Comment by MonfGeiger** [comment]
ok, at this post, I tried this on google chrome with default test settings modified to work, and it still happens when I tried loading this link: https://hentaitake.net/meikoku-gakuen-jutai-hen/

got the same "please disable adblock" message from the 1st post, so I ended up loading some other links in firefox and chrome from the same website, and the same message happens; I think it takes some time for the anti-adblock to load after the initial webpage loads

**Comment by jspenguin2017** [comment]
I think this should fix it: 
```JavaScript
if (a.domCmp(["hentaitake.net"])) {
    a.noAccess("anOptions");
}
```

**Comment by MonfGeiger** [comment]
unfortunately, its not fixed, I tried what I did last post (after updating my adblock protector script and clearing the cache on ublock origin and updating the filters I use, which includes the adblock protector one as well) on both chrome and firefox, and it seems to be on an on/off mood

at times, it doesn't load, and on some it does, so I decide to open a bunch of links on hentaitake.net (some from the recently updated list, and some on its sidebar to the left) through firefox's private mode and chrome's incognito mode, and its the same, sometimes I don't get the warning, and other few times I did after letting the webpage sit a bit

**Comment by jspenguin2017** [comment]
OK, that would be race condition, maybe a filter will help...
Can you try this? 
`hentaitake.net##script:inject(abort-on-property-read.js, anOptions)`

**Comment by MonfGeiger** [comment]
tried it just now, and I think that did it; tried it in chrome and firefox, no problems

**Comment by jspenguin2017** [comment]
Looks like the website is still working. I'll close this issue now, let me know if it breaks again.
